### ISSUE TITLE
WINDOWS: DEFINE_ENUM_FLAG_OPERATORS(SettingsFlag)

### ISSUE THREAD

**Issue by matteocostantini** [embeddedmz/ftpclient-cpp#16]
Add DEFINE_ENUM_FLAG_OPERATORS(SettingsFlag) if WINDOWS or _WINDOWS or _WIN32 is defined!

**Comment by embeddedmz** [comment]
Thanks ! I tried this macro, but it created compile errors (including winnt.h causes troubles under VS2019, sometimes including windows.h helps fixing these errors but it didn't work with the class - it has worked with the unit tests program though).

So, I only added operator | (pipe) overloading for now.
