### ISSUE TITLE
CURLE_URL_MALFORMAT

### ISSUE THREAD

**Issue by nicraMarcin** [embeddedmz/ftpclient-cpp#17]
https://github.com/embeddedmz/ftpclient-cpp/blob/cb78fb54c852a578fd48dcd6a758e8d5e5a6eae4/FTP/FTPClient.cpp#L185

this line changes `ftp://127.0.0.1/` to `ftp:////127.0.0.1////`
shouldn't be?
```cpp
ReplaceString(strURL, "//", "/");
```

**Comment by embeddedmz** [comment]
It's correct even if it looks strange !

Regards.

**Comment by nicraMarcin** [comment]
O, but if I set host to `ftp://127.0.0.1`
```cpp
TPClient.InitSession("ftp://172.28.0.111", 21, "user", "pass");
```
I'm getting error

> [FTPClient][Error] Unable to connect to remote folder /dhcp/ (Error = 3 | URL using bad/illegal format or missing URL).

But 
```cpp
TPClient.InitSession("172.28.0.111", 21, "user", "pass");
```
works. In documentation you provided full url `ftp://IP.IP.IP.IP`

**Comment by embeddedmz** [comment]
Fixed !
