### ISSUE TITLE
ftpserver user 2121 port;upload error Couldn't connect to server

### ISSUE THREAD

**Issue by Dw9** [embeddedmz/ftpclient-cpp#20]
When my ftp server uses port 2121.
my code:

>     CFTPClient FTPClient([](const std::string& strLogMsg){ std::cout << strLogMsg << std::endl; });
>     FTPClient.InitSession(ftpserver.com,2121,user,password);
>     FTPClient.UploadFile(src_file, dst_file);
>     FTPClient.CleanupSession();
i will get "(Error = 7 | Couldn't connect to server)." 
it looks like ftp url Missing port information

**Comment by embeddedmz** [comment]
Hi Dw9,

If you study the code, you will see that you need to use SetActive(true) to be able to use the FTP port, you fed to init session call. I had an issue with active FTP connections, it's an issue with API design and libcurl too...

**Comment by Dw9** [comment]
I tried before，but it's not work;

>      m_bActive =true;
>      if (m_bActive) curl_easy_setopt(m_pCurlSession, CURLOPT_FTPPORT, m_uPort);
it will core dump ,cuz m_uPort is int。In the end my code looks like this：

>  m_bActive =true;
>  if (m_bActive) curl_easy_setopt(m_pCurlSession, CURLOPT_FTPPORT, std::to_string(m_uPort).c_str());
i still get "(Error = 7 | Couldn't connect to server)."

u are right  it's an issue with API design and libcurl too...

**Comment by embeddedmz** [comment]
You can take a look at CURLOPT_FTPPORT documentation https://curl.se/libcurl/c/CURLOPT_FTPPORT.html

How can this even compile with an unsigned integer ??!!?? I don't understand xD

I even forgot the difference between active and passive FTP versions. In my free time, I will see how to sort things out.

Thanks.

**Comment by Dw9** [comment]
> How can this even compile with an unsigned integer ??!!??

libcurl use "variadic" that don't check param type. variadic funcion is unsafe.
I will continually follow this issue,thanks for your offering~😄

**Comment by embeddedmz** [comment]
Thank you for the explanation !

**Comment by embeddedmz** [comment]
@Dw9 This is what I did : if (m_bActive) curl_easy_setopt(m_pCurlSession, CURLOPT_FTPPORT, "-");

I changed the port number by a "-" to let libcurl choose the port range, so with that the API design is still correct.

I will merge your pull request, it will not affect the active mode.

**Comment by embeddedmz** [comment]
Fixed !
