### ISSUE TITLE
cannot find Utf8ToUtf16

### ISSUE THREAD

**Issue by pengzhen80** [embeddedmz/ftpclient-cpp#29]
compile with visual studio 2019,  errors are "cannot identify Utf8ToUtf16"

**Comment by embeddedmz** [comment]
Hi @pengzhen80 

That's strange ! How did you generate the VS2019 solution ? Did you follow the instructions in the README file ?

Apparently you have manually defined the "WINDOWS" preprocessor macro in the FTPClient.cpp file where as you should defined in the header file instead FTPClient.h or it's better for you, if you don't want to use CMake, to define this macro in project settings -> C/C++ -> Preprocessor -> and add WINDOWS macro in the appropriate field (my VS2019 is in french).

You will also have to manage libcurl include directories and add the library in linker inputs if you don't want to use CMake.

Regards.

**Comment by Dw9** [comment]
You need to install curl,and use cmake to generate sln。 it can compile on my computer。
![image](https://user-images.githubusercontent.com/36155473/127419262-e09fb777-7e08-4374-8f65-bb22533c32af.png)

**Comment by pengzhen80** [comment]
Thank you ,  Fixed by add WINDOWN macro;
@embeddedmz
