### ISSUE TITLE
CMake Build Matrix fails for MSVC

### ISSUE THREAD

**Issue by embeddedmz** [embeddedmz/ftpclient-cpp#36]
Hi @ksv87 

The pipeline always fails for MSVC https://github.com/embeddedmz/ftpclient-cpp/actions/runs/2429647821

Apparently, it's because the VS C++ compiler "cl" is missing (by the way, it's github that manages the pipeline ?)

Is it better to remove MSVC from the pipeline file ?

Thanks.

**Comment by ksv87** [comment]
Hi, I check it

**Comment by embeddedmz** [comment]
Thank you @ksv87
