### ISSUE TITLE
error: C3861: “Utf8ToUtf16”: 找不到标识符

### ISSUE THREAD

**Issue by duqingnian** [embeddedmz/ftpclient-cpp#47]
libcurl已经nmake后编译出了libcurl_a.lib，并且在Qt里做了配置
`QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

win32 {
    CONFIG += c++11
    DEFINES += QT_DEPRECATED_WARNINGS

    INCLUDEPATH += "D:\curl-8.0.1\builds\libcurl-vc15-x86-release-static-ipv6-sspi-schannel\include"

    QMAKE_CXXFLAGS += /utf-8

    LIBS += -L"D:\curl-8.0.1\builds\libcurl-vc15-x86-release-static-ipv6-sspi-schannel\lib" \
    -llibcurl_a

} else {
}`
依然提示：
D:\test\curlTest\FTPClient.cpp:631: error: C3861: “Utf8ToUtf16”: 找不到标识符
请问这是为何？

**Comment by embeddedmz** [comment]
I don't understand your problem. I'm sorry.

**Comment by duqingnian** [comment]
> I don't understand your problem. I'm sorry.

Thanks, I forget using english. and I have been resolved this
