### ISSUE TITLE
CTFPClient::ParseURL do not replace [#] to [%23]

### ISSUE THREAD

**Issue by graceon** [embeddedmz/ftpclient-cpp#52]
hi i have a advice
if the file name have [#] it dot not work
and i found CTFPClient::ParseURL  do not process [#]

**Comment by graceon** [comment]
after i add ReplaceString(strURL,"#","%23");
it work ok

**Comment by embeddedmz** [comment]
Hi,

In your case, you have to modify the strings before sending them to the API. It is not up to the API to modify the paths, but to the user to provide them in an appropriate encoding (UTF-8).

Regards.
