### ISSUE TITLE
Windows build using Cmake request for information

### ISSUE THREAD

**Issue by adhaliwal34** [embeddedmz/ftpclient-cpp#54]
Hi,
Thank you and contributors for their efforts! Much appreciated.

This is actually a request for guidance rather than an issue. Let me know if I should move it somewhere else. StackOverflow maybe?

I can build this project on Windows 10 using a slightly modified version of your instructions. Basically I added a vcpkg.json file with the dependencies and then called cmake e.g. `[path to cmake] -B build -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg cmake file]`

This works.

My understanding is that this project is meant to be statically built into another project with a main function (correct me if I am wrong).

So I created a project and added this project as a sub-directory to it. Basically a more complicated set up of [this official CMake tutorial](https://cmake.org/cmake/help/latest/guide/tutorial/Adding%20a%20Library.html)

My project directory looks like this:

[project folder]/ftp_automation_cpp/ftpclient-cpp/
[project folder]/ftp_automation_cpp/CMakeLists.txt
[project folder]/ftp_automation_cpp/ftp_automation.cpp
[project folder]/ftp_automation_cpp/vcpkg.json

vckpg.json
```
{
  "dependencies": [
	{
		"name" : "curl",
		"features" : [ "openssl",	"ssh" ]
	},
    "gtest"
  ]
}
```

ftp_automation.cpp
```
#include <iostream>
#include <string>
#include "FTPClient.h"

int main(int argc, char* argv[])
{
  std::cout << "Hello, world!"
            << std::endl;
  return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.27)
project(FTP_Automation VERSION 0.1)
add_executable(ftp_automation ftp_automation.cpp)

add_subdirectory(ftpclient-cpp)

target_include_directories(ftp_automation PUBLIC
                          "${PROJECT_BINARY_DIR}"
                          "${PROJECT_SOURCE_DIR}/ftpclient-cpp"
                          )

add_library(FTPClient STATIC)
target_sources(FTPClient PUBLIC "${PROJECT_SOURCE_DIR}/ftpclient-cpp/FTP/FTPClient.cpp")
target_sources(FTPClient PUBLIC "${PROJECT_SOURCE_DIR}/ftpclient-cpp/FTP/CurlHandle.cpp")

target_link_libraries(ftp_automation PUBLIC FTPClient)
```

This builds and generates the .sln file but on opening it VS 2022 says there is already a ftpclient-cpp project and the cpp files are duplicated in my project.

**Comment by adhaliwal34** [comment]
Also it occurred to me that maybe I shouldn't build the whole ftpclient-cpp project in my own project. Maybe I should build it separately and move only certain files across? e.g. lib files and dlls.

**Comment by adhaliwal34** [comment]
I'm closing this. It's not really related to this project. It's more a build question.

**Comment by embeddedmz** [comment]
Hi,

don't complicate your life, choose the simplest and easiest solution to integrate this class into your project. it's a free project, you can do what you want with it.

Best regards.

**Comment by adhaliwal34** [comment]
Good advice, unfortunately I'm very good at complicating my life :)

**Comment by embeddedmz** [comment]
don't worry, you're not the only one and that's why our lives suck :laughing:
